name: Lint
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AWS XRay SDK Node Repository @ default branch latest
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0

      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 #v3.9.1
        with:
          node-version: 16.x

      - run: npm install -g npm@8.19.4

      - name: Cache NPM modules
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c #v3.5.0
        with:
          path: |
            node_modules
            package-lock.json
            packages/*/node_modules
            packages/*/package-lock.json
          key: lint-${{ runner.os }}-${{ hashFiles('package.json', 'packages/*/package.json') }}-06142023

      - name: Bootstrap
        run: |
          npm ci
          npx lerna bootstrap --no-ci --hoist

      - name: Lint
        run: npx lerna run lint
